body_test_welcome_common: &body_test_welcome_common
  adapter: postgresql
  encoding: utf8
  host: localhost
  password: password
  pool: 5
  username: postgres

development:
  <<: *body_test_welcome_common
  database: bt_funnel_development

test:
  <<: *body_test_welcome_common
  database: bt_funnel_test

production:
  <<: *body_test_welcome_common
  database: bt_funnel_production
